### ISSUE TITLE
Plugin doesn't load properly

### ISSUE THREAD

**Issue by rohrkemper** [hjallehallin/homebridge-twine-temp#1]
I'd love to get this working. Any ideas?

{
  "accessory": "TwineTemp",
  "name": "Temperature",
  "twine_id": "f3hfskjhdf2u34udf732rfds",
  "email": "me@me.com",
  "password": "asdf"
}

[3/28/2021, 12:49:09 PM] TypeError: Cannot read property 'length' of undefined
    at presentValues (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/values.js:18:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/index.js:12:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/index.js:61:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[3/28/2021, 12:49:09 PM] Got SIGTERM, shutting down Homebridge...
[3/28/2021, 12:49:09 PM] TypeError: Cannot read property 'length' of undefined
    at presentValues (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/values.js:18:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/index.js:12:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/index.js:61:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[3/28/2021, 12:49:09 PM] TypeError: Cannot read property 'length' of undefined
    at presentValues (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/values.js:18:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/index.js:12:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/index.js:61:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[3/28/2021, 12:49:09 PM] TypeError: Cannot read property 'length' of undefined
    at presentValues (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/values.js:18:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/presenters/index.js:12:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/bowline/lib/index.js:61:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-twine-temp/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)

**Comment by hjallehallin** [comment]
Wow, I had forgot this plugin completely. Sadly I've misplaced my twine as well. I have a vague memory of needing to install the dependencies manually and globally for this to work. Have you tried that? e.g. `npm install -g bowline`
